function headvol = initHeadvol()

headvol = struct( ...
                 'pathname', '', ...
                 'name', 'headvol', ...
                 'handles',struct('hSurf',[], 'hAxes',[], 'axes', gca), ...
                 'img',uint8([]), ...
                 'imgOrig',uint8([]), ...
                 'center',[], ...
                 'mesh',initMesh(), ...
                 'tiss_prop',struct(), ...
                 'T_2digpts',eye(4), ...
                 'T_2mc',eye(4), ...
                 'orientation', '', ...
                 'orientationOrig', '', ...
                 'checkCompatability',[], ...
                 'isempty',@isempty_loc, ...                 
                 'prepObjForSave',[] ...                 
                );

% --------------------------------------------------------------
function b = isempty_loc(headvol)

b = false;
if isempty(headvol.img)
    b = true;
end

