function paths = getpaths()

paths = {...
    '/', ...
    '/DISPLAY', ...
    '/DISPLAY/plotProbeGUI', ...
    '/INSTALL', ...
    '/PACKAGES', ...
    '/PACKAGES/AtlasViewerGUI', ...
    '/PACKAGES/AtlasViewerGUI/Axesv', ...
    '/PACKAGES/AtlasViewerGUI/Data', ...
    '/PACKAGES/AtlasViewerGUI/Data/Colin', ...
    '/PACKAGES/AtlasViewerGUI/Digpts', ...
    '/PACKAGES/AtlasViewerGUI/ForwardModel', ...
    '/PACKAGES/AtlasViewerGUI/Group', ...
    '/PACKAGES/AtlasViewerGUI/Guiobj', ...
    '/PACKAGES/AtlasViewerGUI/HbConc', ...
    '/PACKAGES/AtlasViewerGUI/Headsurf', ...
    '/PACKAGES/AtlasViewerGUI/Headvol', ...
    '/PACKAGES/AtlasViewerGUI/ImgRecon', ...
    '/PACKAGES/AtlasViewerGUI/Labelssurf', ...
    '/PACKAGES/AtlasViewerGUI/Pialsurf', ...
    '/PACKAGES/AtlasViewerGUI/Probe', ...
    '/PACKAGES/AtlasViewerGUI/Probe/registerDigpts', ...
    '/PACKAGES/AtlasViewerGUI/Probe/registerSprings', ...
    '/PACKAGES/AtlasViewerGUI/Refpts', ...
    '/PACKAGES/AtlasViewerGUI/Tools', ...
    '/PACKAGES/AtlasViewerGUI/Utils', ...
    '/PACKAGES/AtlasViewerGUI/Utils/fs2viewer', ...
    '/PACKAGES/AtlasViewerGUI/Utils/nifti', ...
    '/PACKAGES/AtlasViewerGUI/ezmapper', ...
    '/PACKAGES/AtlasViewerGUI/freesurfer', ...
    '/PACKAGES/AtlasViewerGUI/iso2mesh', ...
    '/PACKAGES/AtlasViewerGUI/iso2mesh/bin', ...
    '/PACKAGES/AtlasViewerGUI/metch', ...
    '/PACKAGES/EasyNIRS', ...
    '/PACKAGES/EasyNIRS/Export', ...
    '/PACKAGES/EasyNIRS/LoadSaveData', ...
    '/PACKAGES/EasyNIRS/NirsFiles', ...
    '/PACKAGES/EasyNIRS/PlotProbe', ...
    '/PACKAGES/EasyNIRS/Processing', ...
    '/PACKAGES/SDgui', ...
    '/PACKAGES/SDgui/lambda', ...
    '/PACKAGES/SDgui/optode_tbls', ...
    '/PACKAGES/SDgui/optode_tbls2', ...
    '/PACKAGES/SDgui/probe_geometry_axes', ...
    '/PACKAGES/SDgui/probe_geometry_axes2', ...
    '/PACKAGES/SDgui/sample_data', ...
    '/PACKAGES/SDgui/sd_data', ...
    '/PACKAGES/SDgui/sd_file', ...
    '/PACKAGES/SDgui/utils', ...
    '/PACKAGES/Utils', ...
    '/PACKAGES/stimGUI', ...
    '/PACKAGES/tMCimg', ...
    '/PACKAGES/tMCimg/bin/Darwin', ...
    '/PACKAGES/tMCimg/bin/Linux', ...
    '/PACKAGES/tMCimg/bin/Win', ...
    '/UTILITIES', ...
    '/UTILITIES/REGRESSORS', ...
    '/UTILITIES/Wavelet', ...
    '/UTILITIES/iWLS' ...
    };



