function refpts = initRefpts(handles)

refpts = struct( ...
   'pathname','', ...
   'name', 'refpts', ...
   'handles', struct(...
      'labels',[], ...
      'circles',[], ...
      'radiobuttonShowRefptsLabels',[], ...
      'radiobuttonShowRefptsCircles',[], ...
      'menuItemCalculateRefpts',[], ...
      'menuItemRefptsToCortex', [], ...
      'hCortexProjection', [], ...
      'hProjectionRays', [], ...
      'selected',[], ...
      'textSize', 9, ...
      'circleSize', 14, ...
      'color',[.2 .05 .1], ...
      'axes',[] ...
   ), ...
   'pos',zeros(0,3), ...
   'labels',[], ...
   'T_2vol',eye(4), ...
   'center', [], ...
   'orientation', '', ...
   'checkCompatability',[], ...
   'isempty',@isempty_loc, ...
   'prepObjForSave',[], ...
   'cortexProjection', struct(...
                              'vertices',[], ...
                              'iFaces',[], ...
                              'iVertices',[], ...
                              'pos',[] ...
                             ) ...
);

% This has to be done outpsid of call to struct. Apparently in matlkab you can't
% assign a cell array to a field from struct(). Instead of assigning a cell
% to that field it makes a an array of structs with dimension the size of
% the cell. 
refpts.labels = {};


if exist('handles','var')
    refpts.handles.radiobuttonShowRefptsLabels = handles.radiobuttonShowRefptsLabels;
    refpts.handles.radiobuttonShowRefptsCircles = handles.radiobuttonShowRefptsCircles;
    set(refpts.handles.radiobuttonShowRefptsLabels,'enable','off');
    set(refpts.handles.radiobuttonShowRefptsLabels,'value',0);
    set(refpts.handles.radiobuttonShowRefptsCircles,'enable','off');
    set(refpts.handles.radiobuttonShowRefptsCircles,'value',0);

    refpts.handles.menuItemCalculateRefpts = handles.menuItemCalculateRefpts;
    set(refpts.handles.menuItemCalculateRefpts,'enable','off');
    refpts.handles.axes = handles.axesSurfDisplay;
    
    refpts.handles.menuItemRefptsToCortex = handles.menuItemRefptsToCortex;
end



% --------------------------------------------------------------
function b = isempty_loc(refpts)

b = false;
if isempty(refpts.pos)
    b = true;
end
if isempty(refpts.labels)
    b = true;
end

